[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20", "gcc"]

[phases.install]
cmds = ["python3 -m pip install -r api/requirements.txt", "cd frontend && npm install"]

[phases.build]
cmds = ["chmod +x build.sh && ./build.sh"]

[start]
cmd = "chmod +x api/start.sh && cd api && ./start.sh"
