providers = ["python", "node"]

[phases.setup]
nixPkgs = ["gcc"]

[phases.install]
cmds = ["pip install -r api/requirements.txt", "cd frontend && npm install"]

[phases.build]
cmds = ["chmod +x build.sh && ./build.sh"]

[start]
cmd = "chmod +x api/start.sh && cd api && ./start.sh"
