# Generated by Django 5.2.4 on 2026-02-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='Web Development', help_text="e.g., 'Web Dev', 'AI', 'UI/UX'", max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show prominently on the home page'),
        ),
    ]
