# Generated by Django 6.0.2 on 2026-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.FileField(help_text='Upload a PNG/SVG icon', upload_to='skills/icons/')),
                ('order', models.IntegerField(default=0, help_text='Order of appearance')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
