# Generated by Django 6.0.2 on 2026-02-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text="FontAwesome class (e.g., 'fa-brands fa-github'). Leave blank for auto-detection.", max_length=100, null=True),
        ),
    ]
