# Generated by Django 5.2.4 on 2026-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text="Comma-separated technologies (e.g., 'SQL, FastAPI, Django')", max_length=255)),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('video', models.FileField(blank=True, help_text='Optional video showcase', null=True, upload_to='projects/videos/')),
                ('live_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
