# Generated by Django 6.0.2 on 2026-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_project_category_project_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Saad', max_length=200)),
                ('title', models.CharField(default='Software Engineer', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
