# Generated by Django 6.0.2 on 2026-02-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_sociallink_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload a custom image icon. Takes priority over icon class.', null=True, upload_to='social_icons/'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text="FontAwesome class (e.g., 'fa-brands fa-github').", max_length=100, null=True),
        ),
    ]
